<?php
$section_params = array (
	'row_padding_top' => '118',
	'row_padding_bottom' => '100',
	'mbuilder-id' => '14',
	'content' => '[vc_column][md_text  md_text_alignment="center" md_text_title_line_height="40" md_text_desc_line_height="41" md_text_title_bottom_space="37" md_text_separator_bottom_space="10" md_text_description_bottom_space="90" md_text_title_separator="no" md_text_separator_width="110" md_text_separator_height="5" md_text_separator_color="rgb(0, 255, 153)" md_text_style="solid" md_text_solid_color="rgba(20,20,20,1)" md_text_gradient_color="pixflow_base64eyJjb2xvcjEiOiIjODcwMmZmIiwiY29sb3IyIjoiIzA2ZmY2ZSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0=" md_text_title_size="32" md_text_letter_space="0" md_text_hover_letter_space="0" md_text_easing="cubic-bezier(0.215, 0.61, 0.355, 1)" md_text_use_title_custom_font="yes" md_text_title_google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:700%20bold%20regular%3A700%3Anormal" md_text_number="1" md_text_title1="pixflow_base64PGRpdj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxOHB4OyI+Q1JFQVRJVkUgU1RVRElPPC9zcGFuPjwvZGl2Pg==" md_text_title2="Typography Shortcode" md_text_title3="Typography Shortcode" md_text_title4="Typography Shortcode" md_text_title5="Typography Shortcode" md_text_content_size="14" md_text_content_color="rgba(20,20,20,1)" md_text_use_desc_custom_font="yes" md_text_desc_google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal" md_text_use_button="no" md_text_button_style="fade-oval" md_text_button_size="standard" left_right_padding="0" md_text_button_text="READ MORE" md_text_button_icon_class="icon-angle-right" md_text_button_color="rgba(0,0,0,1)" md_text_button_text_color="rgba(255,255,255,1)" md_text_button_bg_hover_color="rgb(0,0,0)" md_text_button_hover_color="rgb(255,255,255)" md_text_button_url="#" md_text_button_target="_self" md_text_animation_type="fade" md_text_animation_speed="200" md_text_animation_delay="0.0" md_text_animation_position="center" md_text_animation_show="once" md_text_animation_easing="Quart.easeInOut" md_text_parallax_speed="1"]<p><span style="font-size: 38px">Build Your Entire Site in Minutes!</span></p>[/md_text][md_video  md_video_host="youtube" md_video_url_mp4="" md_video_url_webm="" md_video_url_ogg="" md_video_url_youtube="https://www.youtube.com/watch?v=tcxlSrYEkq8" md_video_url_vimeo="" md_video_style="squareImage" md_video_solid_color="rgba(20,20,20,1)" md_video_image="http://theme.pixflow.net/massive-dynamic/creative-company/wp-content/uploads/sites/76/2018/11/kelly-sikkema-291518-unsplash.jpg" md_video_size="100" md_video_animation_type="fade" md_video_animation_speed="200" md_video_animation_delay="0.0" md_video_animation_position="center" md_video_animation_show="once" md_video_animation_easing="Quart.easeInOut" md_video_parallax_speed="1"][/md_video][/vc_column]',
);


