<?php
$section_params = array (
	'type_width' => 'full_size',
	'box_size_states' => 'content_box_size',
	'el_class' => '',
	'row_fit_to_height' => 'yes',
	'row_vertical_align' => 'yes',
	'row_equal_column_heigh' => 'enable',
	'row_content_vertical_align' => '0',
	'row_type' => 'image',
	'background_color' => 'rgba(255,255,255,1)',
	'row_webm_url' => '',
	'row_mp4_url' => '',
	'background_color_image' => 'rgba(0,0,0,0.2)',
	'row_gradient_color' => 'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0=',
	'row_image' => 'http://theme.pixflow.net/massive-dynamic/creative-company/wp-content/uploads/sites/76/2018/11/jose-aljovin-331066-unsplash.jpg',
	'row_image_position' => 'default',
	'row_image_position_gradient' => 'fit',
	'row_bg_image_size_tab_image' => 'cover',
	'row_bg_image_size_tab_gradient' => 'cover',
	'row_bg_repeat_image_gp' => 'no',
	'row_bg_repeat_gradient_gp' => 'no',
	'row_padding_top' => '123',
	'row_padding_bottom' => '45',
	'row_padding_right' => '0',
	'row_padding_left' => '0',
	'row_margin_top' => '0',
	'row_margin_bottom' => '0',
	'row_inner_shadow' => 'no',
	'row_sloped_edge' => 'no',
	'row_slope_edge_position' => 'top',
	'row_sloped_edge_angle' => '-3',
	'parallax_status' => 'enable',
	'parallax_speed' => '0',
	'align' => 'yes',
	'mbuilder-id' => '1',
	'content' => '[vc_column][md_text  md_text_alignment="center" md_text_title_line_height="50" md_text_desc_line_height="20" md_text_title_bottom_space="33" md_text_separator_bottom_space="10" md_text_description_bottom_space="37" md_text_title_separator="no" md_text_separator_width="110" md_text_separator_height="5" md_text_separator_color="rgb(0, 255, 153)" md_text_style="solid" md_text_solid_color="rgb(255, 255, 255)" md_text_gradient_color="pixflow_base64eyJjb2xvcjEiOiIjODcwMmZmIiwiY29sb3IyIjoiIzA2ZmY2ZSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0=" md_text_title_size="32" md_text_letter_space="0" md_text_hover_letter_space="0" md_text_easing="cubic-bezier(0.215, 0.61, 0.355, 1)" md_text_use_title_custom_font="yes" md_text_title_google_fonts="font_family:Montserrat%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal" md_text_number="1" md_text_title1="pixflow_base64PGRpdj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiA0MHB4OyI+Q3JlYXRlIFlvdXIgV2Vic2l0ZS48L3NwYW4+PC9kaXY+" md_text_title2="Typography Shortcode" md_text_title3="Typography Shortcode" md_text_title4="Typography Shortcode" md_text_title5="Typography Shortcode" md_text_content_size="14" md_text_content_color="rgba(20,20,20,1)" md_text_use_desc_custom_font="yes" md_text_desc_google_fonts="font_family:Poppins%3A300%2Cregular%2C500%2C600%2C700|font_style:300%20light%20regular%3A300%3Anormal" md_text_use_button="yes" md_text_button_style="fill-oval" md_text_button_size="standard" left_right_padding="10" md_text_button_text="GET STARTED" md_text_button_icon_class="icon-empty" md_text_button_color="rgb(65, 87, 248)" md_text_button_text_color="rgba(255,255,255,1)" md_text_button_bg_hover_color="rgb(255, 255, 255)" md_text_button_hover_color="rgb(0, 0, 0)" md_text_button_url="#" md_text_button_target="_self" md_text_animation_type="fade" md_text_animation_speed="200" md_text_animation_delay="0.0" md_text_animation_position="center" md_text_animation_show="once" md_text_animation_easing="Quart.easeInOut" md_text_parallax_speed="1"]<p><span style="font-size: 20px;color: #ffffff">We provides you a highly customized version of Massive Dynamic with</span></p>
<p><span style="font-size: 20px;color: #ffffff"> unique elements all available for use via drag &amp; drop.</span></p>[/md_text][/vc_column]',
);


