<?php
$section_params = array (
    'type_width' => 'full_size',
    'box_size_states' => 'content_box_size',
    'el_class' => '',
    'row_fit_to_height' => 'enable',
    'row_vertical_align' => 'enable',
    'row_equal_column_heigh' => 'enable',
    'row_content_vertical_align' => '0',
    'row_type' => 'image',
    'background_color' => 'rgba(255,255,255,1)',
    'row_webm_url' => '',
    'row_mp4_url' => '',
    'background_color_image' => 'rgba(0, 0, 0, 0.36)',
    'first_color' => '#000',
    'second_color' => '#000',
    'row_gradient_color' => 'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0=',
    'row_image' => 'http://theme.pixflow.net/massive-dynamic/creative-production/wp-content/uploads/sites/74/2018/11/parker-whitson-571424-unsplash.jpg',
    'row_image_position' => 'default',
    'row_image_position_gradient' => 'fit',
    'row_bg_image_size_tab_image' => 'cover',
    'row_bg_image_size_tab_gradient' => 'cover',
    'row_bg_repeat_image_gp' => 'no',
    'row_bg_repeat_gradient_gp' => 'no',
    'row_padding_top' => '260',
    'row_padding_bottom' => '281',
    'row_padding_right' => '0',
    'row_padding_left' => '0',
    'row_margin_top' => '0',
    'row_margin_bottom' => '0',
    'row_inner_shadow' => 'no',
    'row_sloped_edge' => 'no',
    'row_slope_edge_position' => 'top',
    'row_sloped_edge_color' => '#000',
    'row_sloped_edge_angle' => '-3',
    'parallax_status' => 'enable',
    'parallax_speed' => '0',
    'align' => 'enable',
    'mbuilder-id' => '30',
    'content' => '[vc_column  el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable" 31"][md_live_text  meditor_letter_spacing="0" meditor_line_height="1"                     md_live_text_animation_speed="800" md_live_text_animation_position="left" md_live_text_animation_show="scroll" md_live_text_animation_easing="Power4.easeOut" md_live_text_animation="yes" md_live_text_animation_delay="0.4"  align="left" 33"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsgZm9udC1zaXplOiAzNXB4OyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyIgY2xhc3M9ImtlZXAtdGV4dC1zZWxlY3RlZCI+PHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsgZm9udC1zaXplOiAzNXB4OyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMzVweDsgbGluZS1oZWlnaHQ6IDEuMmVtOyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyI+PHNwYW4gZGF0YS1mb250LXdlaWdodD0iNjAwIiBzdHlsZT0iZm9udC1zdHlsZTogbm9ybWFsOyBsaW5lLWhlaWdodDogMS4yZW07IGZvbnQtc2l6ZTogMzVweDsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS4yZW07IGZvbnQtc2l6ZTogMzVweDsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiIGNsYXNzPSIiPjxzcGFuIGRhdGEtZm9udC13ZWlnaHQ9IjQwMCIgc3R5bGU9ImZvbnQtc3R5bGU6IG5vcm1hbDsgZm9udC1zaXplOiAzNXB4OyBmb250LWZhbWlseTogTW9udHNlcnJhdDsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiIGNsYXNzPSIiPjxiIHN0eWxlPSJmb250LXNpemU6IDM1cHg7IGNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7Ij48c3BhbiBkYXRhLWZvbnQtd2VpZ2h0PSI0MDAiIHN0eWxlPSJmb250LXN0eWxlOiBub3JtYWw7IGZvbnQtZmFtaWx5OiBNb250c2VycmF0OyBmb250LXdlaWdodDogNDAwOyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyIgY2xhc3M9IiI+TWVldCB0aGUgdGVhbTwvc3Bhbj48L2I+PC9zcGFuPjwvc3Bhbj48L3NwYW4+PC9zcGFuPjwvc3Bhbj48L3NwYW4+PC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIA==[/md_live_text][vc_empty_space  height="40"][/vc_empty_space][md_button  button_style="fill-rectangle" button_size="standard" left_right_padding="10" button_align="left" button_text="SEE MORE" button_icon_class="icon-empty" button_color="rgb(255, 255, 255)" button_text_color="rgb(0, 0, 0)" button_bg_hover_color="rgb(65, 87, 248)" button_hover_color="#FFF" button_url="#" button_target="_self" md_button_animation="yes" md_button_animation_type="fade" md_button_animation_speed="800" md_button_animation_delay="0.5" md_button_animation_position="left" md_button_animation_show="scroll" md_button_animation_easing="Power4.easeOut" md_button_parallax_speed="1" align="left" 35"][/md_button][/vc_column][vc_column  width="6/12" css=".vc_column-inner.md_col-5be7ec1a3f785{padding-right:184px!important;}"    padding_right="184" 32"][md_live_text  is_new_shortcode="yes"  meditor_line_height="1.7" meditor_letter_spacing="0"  36"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjdlbTsiIGNsYXNzPSJrZWVwLXRleHQtc2VsZWN0ZWQiPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogTW9udHNlcnJhdDsgbGluZS1oZWlnaHQ6IDEuN2VtOyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGZvbnQtc2l6ZTogMTZweDsgbGluZS1oZWlnaHQ6IDEuN2VtOyI+PHNwYW4gZGF0YS1mb250LXdlaWdodD0iNDAwIiBzdHlsZT0iZm9udC1zdHlsZTogbm9ybWFsOyBmb250LWZhbWlseTogTW9udHNlcnJhdDsgZm9udC13ZWlnaHQ6IDQwMDsgbGluZS1oZWlnaHQ6IDEuN2VtOyIgY2xhc3M9IiI+TWFzc2l2ZSBEeW5hbWljIGhhcyBvdmVyIDEwIHllYXJzIG9mIGV4cGVyaWVuY2UgaW4gRGVzaWduLCBUZWNobm9sb2d5IGFuZCBNYXJrZXRpbmcuIFdlIHRha2UgcHJpZGVvIGluIGRlbGl2ZXJpbmcgSW50ZWxsaWdlbnQgRGVzaWducyBhbmQgRW5nYWdpbmcgRXhwZXJpZW5jZXMgZm9yIGNsaWVudHMgYWxsIG92ZXIgdGhlIFdvcmxkLjwvc3Bhbj48L3NwYW4+PC9zcGFuPjwvc3Bhbj4gICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIA==[/md_live_text][/vc_column]',
);


