<?php 
$headings = array (
    'Headings' => array(
        'h1' => array(
            'label' => __( 'Heading 1', 'exponent' ),
            'selector' => 'h1',
            'expose'   => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(
                'font-family' => 'schemes:primary',
                'font-variant' => '600',
                'font-size' => '46px',
                'text-transform' => 'none',
                'letter-spacing' => '-0.014em',
                'line-height' => '60px',
                'color' => '#343638',
            )
        ),
        'h2' => array(
            'label' => __( 'Heading 2', 'exponent' ),
            'selector' => 'h2',
            'expose'   => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(
                'font-family' => 'schemes:primary',
                'font-variant' => '600',
                'font-size' => '40px',
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '54px',
                'color' => '#343638',
            )
        ),
        'h3' => array(
            'label' => __( 'Heading 3', 'exponent' ),
            'selector' => 'h3',
            'expose'    => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(
                'font-family' => 'schemes:primary',
                'font-variant' => '600',
                'font-size' => '32px',
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '46px',
                'color' => '#343638',
            )
        ),
        'h4' => array(
            'label' => __( 'Heading 4', 'exponent' ),
            'selector' => 'h4',
            'expose'    => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(
                'font-family' => 'schemes:primary',
                'font-variant' => '600',
                'font-size' => '24px',
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '36px',
                'color' => '#343638',
            )
        ),
        'h5' => array(
            'label' => __( 'Heading 5', 'exponent' ),
            'selector' => 'h5, 
                .exp-wc-cart-collaterals-inner .cart_totals h2, 
                .woocommerce-billing-fields h3,
                .exp-wc-cart-title,
                #ship-to-different-address,
                .woocommerce-customer-details .woocommerce-column__title,
                .woocommerce-account.woocommerce-edit-address h3,
                #order_review_heading,
                .exp-posts-nav-post-title',
            'expose'    => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(
                'font-family' => 'schemes:primary',
                'font-variant' => '600',
                'font-size' => '17px',
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '30px',
                'color' => '#343638',
            )
        ),
        'h6' => array(
            'label' => __( 'Heading 6', 'exponent' ),
            'selector' => 'h6,
                .testimonial-author-role.h6-font,
                .menu-card-title,
                .menu-card-item-price,
                .slider-counts,
                .woocommerce-mini-cart__total strong,
                .variations .label,
                .exp-wc-meta-label,
                .exp-wc-shop-attribute-label,
                .cart_totals h2,
                .woocommerce-orders-table th,
                .upsells > h2,
                .related > h2,
                .woocommerce-table--order-details thead th,
                .woocommerce-orders-table a,
                .wc_payment_method label,
                .woocommerce-checkout-review-order thead th,
                .wishlist_table th,
                .exp-wc-product-share-label,
                .yith-wcwl-share-title,
                .woocommerce-Reviews #reply-title,
                .woocommerce-checkout-review-order tfoot .woocommerce-Price-amount,
                .stock,
                .woocommerce-table--order-details tfoot .woocommerce-Price-amount,
                .woocommerce-Address-title a,
                .wc-tabs,
                .exp-wc-review-author,
                a.bbp-forum-title,
                #bbpress-forums fieldset.bbp-form label,
                .bbp-topic-title a.bbp-topic-permalink,
                #bbpress-forums ul.forum-titles li,
                #bbpress-forums ul.bbp-replies li.bbp-header',  
            'expose'    => true,
            'responsive' => true, 
            'img' => get_template_directory_uri().'/img/typehub/h1_h6.jpg',
            'options' => array(  
                'font-family' => 'schemes:primary', 
                'font-variant' => '600',  
                'font-size' => '15px', 
                'text-transform' => 'none', 
                'letter-spacing' => '-0.01em', 
                'line-height' => '26px',
                'color' => '#343638',
            )
        ),
        'h7' => array(
            'label' => __( 'Heading 7', 'exponent' ),
            'selector' => '.widget_recent_comments a, .widget_rss .rsswidget, .widget_rss cite, .cart_totals th, .woocommerce-checkout-review-order-table tfoot th, .woocommerce-table--order-details tfoot th, .exp-recent-posts-widget-post-title, .widget_recent_entries a',
            'expose'    => true,
            'responsive' => true, 
            'img' => '',
            'options' => array(  
                'font-family' => 'schemes:primary', 
                'font-variant' => '600',  
                'font-size' => '14px', 
                'text-transform' => 'none', 
                'letter-spacing' => '-0.01em', 
                'line-height' => '22px',
                'color' => '#343638',
            )
        ),
        'h8' => array(
            'label' => __( 'Heading 8', 'exponent' ),
            'selector' => '',  
            'expose'    => true,
            'responsive' => true, 
            'img' => '',
            'options' => array(  
                'font-family' => 'schemes:primary', 
                'font-variant' => '600',  
                'font-size' => '12px', 
                'text-transform' => 'none', 
                'letter-spacing' => '0px', 
                'line-height' => '16px',
                'color' => 'rgba(0, 0, 0, 0.45)',
            )
        ),
        'h9' => array(
            'label' => __( 'Heading 9', 'exponent' ),
            'selector' => '.exp-posts-nav-post-location, .exp-read-more-underlined, .pages_list a',  
            'expose'    => true,
            'responsive' => true, 
            'img' => get_template_directory_uri().'/img/typehub/h9.jpg',
            'options' => array(  
                'font-family' => 'schemes:primary', 
                'font-variant' => '600',  
                'font-size' => '11px', 
                'text-transform' => 'uppercase', 
                'letter-spacing' => '1px', 
                'line-height' => '14px',
                'color' => 'rgba(0, 0, 0, 0.45)',
            )
        ),
        'body' => array(
            'label' => __( 'Body - Main Text', 'exponent' ),
            'selector' => 'body,
                .special-heading-wrap .caption-wrap .body-font',
            'expose'    => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/body.jpg',  
            'options' => array( 
                'font-family' => 'schemes:secondary', 
                'font-variant' => '400', 
                'font-size' => '16px', 
                'text-transform' => 'none',
                'letter-spacing' => '0px',
                'line-height' => '28px',
                'color' => '#77797d',
            )
        ),
        'body_1' => array(
            'label' => __( 'Body - Variant 1', 'exponent' ),
            'selector' => '',
            'expose'    => true,
            'responsive' => true,
            'img' => '',  
            'options' => array( 
                'font-family' => 'schemes:secondary', 
                'font-variant' => '400', 
                'font-size' => '15px', 
                'text-transform' => 'none',
                'letter-spacing' => '0px',
                'line-height' => '25px',
                'color' => '#848991',
            )
        ),
        'body_2' => array(
            'label' => __( 'Body - Variant 2', 'exponent' ),
            'selector' => '',
            'expose'    => true,
            'responsive' => true,
            'img' => '',  
            'options' => array( 
                'font-family' => 'schemes:secondary', 
                'font-variant' => '400', 
                'font-size' => '20px', 
                'text-transform' => 'none',
                'letter-spacing' => '0px',
                'line-height' => '32px',
                'color' => '#848991',
            )
        ),
        'quote' => array(
            'label' => __( 'Blockquote', 'exponent' ),
            'selector' => 'blockquote',
            'expose'    => true,
            'responsive' => true,
            'img' => get_template_directory_uri().'/img/typehub/quote.jpg',  
            'options' => array( 
                'font-family' => 'schemes:primary', 
                'font-variant' => '400', 
                'font-size' => '21px', 
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '35px',
                'color' => '#343638',
            )
        ),
        'entry_title'   => array (
            'label'     => __( 'Global Page Title', 'exponent' ),
            'selector'  => '.exp-post-entry-title',
            'responsive'=> true,
            'img'       => get_template_directory_uri().'/img/typehub/entry_title.jpg',
            'options'   => array (
                'font-family' => 'schemes:primary', 
                'font-variant' => '600', 
                'font-size' => '32px', 
                'text-transform' => 'none',
                'letter-spacing' => '-0.01em',
                'line-height' => '46px',
                'color' => '#343638',
            )
        ),
        'post_nav_title' => array(
            'label' => __( 'Global Post / Portfolio Navigation', 'exponent' ),
            'selector' => '.exp-posts-nav-post-title',
            'img' => get_template_directory_uri().'/img/typehub/post_nav_title.jpg',
            'responsive' => true,
            'options' => array(
                'font-family'   => 'schemes:primary',
                'font-variant'   => '600',
                'font-size'     => '17px',
                'text-transform' => 'none',
                'letter-spacing' => '0px',
                'line-height'   => '30px',
                'color' => '#343638',
            )
        ),

    )
);

return $headings;